# Generated by Django 4.2.3 on 2023-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_actor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
