# Generated by Django 4.2.3 on 2023-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierelation',
            name='text',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Сообщение'),
        ),
    ]
